baseURL: https://datasci.brown.edu/ccvcon
languageCode: "en-us"
title: "CCV·Con"
theme: brown-simple
publishDir: public
enableRobotsTXT: true

params:
  title: CCV·Con
  full_title: Center for Computation & Visualization Conference
  subtitle: not just Oscar
  info:
    description: "The Brown University Center for Computation and Visualization (CCV) is proud to announce its first annual conference! This will feature talks and workshops related to a broad range of topics in research computing, including: high-performance computing, machine learning, reproducible science, data visualization, bioinformatics, research infrastructure, and software engineering."
    date:
      start: Monday Oct 28
      end:  Friday Nov 1
      year: 2019
      time_start: 3 - 5pm
    location:
      building: Data Science Initiative - 164 Angell Street, 3rd Floor, Brown University
      city: Providence, RI
    note: "<i class='fad fa-cookie'></i> <i class='fad fa-glass-citrus'></i> Light snacks and beverages will be served every day at 3pm. <br><i class='fad fa-cocktail'></i> <i class='fad fa-cheese'></i> There will be a reception after the keynote on Friday November 1st, open to all attendees. <br><i class='fad fa-shopping-bag'></i>  The first 50 people to arrive will get a swag of the day (see below)."
  program:
    - time: Monday, October 28
      session: Reproducible Science + CCV Showcase
      title: Reproducible Science
      speaker: Ashok Ragavendran, Isabel Restrepo
      swag: "Moleskine<sup class='reg'>&#9415;</sup> notebook"
      fa: book
    - time: Tuesday, October 29
      session: Research Infrastructure + Visualization
      title: Research Infrastructure + Visualization
      speaker: Mete Tunca, Ben Knörlein
      swag: water bottle
      fa: wine-bottle
    - time: Wednesday, October 30
      session: Data Science + Machine Learning
      title: Data Science + Machine Learning
      speaker: Andras Zsom, Paul Stey
      swag: tote bag
      fa: shopping-bag
    - time: Thursday, October 31
      session: High-performance Computing
      title: High-performance Computing
      speaker: Helen Kershaw
      swag: hat
      fa: hat-wizard
    - time: Friday, November 1
      session: But also Oscar + Keynote
      title: But also Oscar + Keynote + Reception
      speaker: Linnea Wolfe, Mete Tunca, Paul Stey.
      swag: mug
      fa: mug
